require 'autoparts/version'
require 'autoparts/errors'
require 'autoparts/path'
require 'autoparts/util'
require 'autoparts/cli_parser'
require 'autoparts/package'
require 'autoparts/commands/help'
require 'autoparts/commands/init'
require 'autoparts/commands/list'
require 'autoparts/commands/search'
require 'autoparts/commands/install'
require 'autoparts/commands/uninstall'
require 'autoparts/commands/purge'
require 'autoparts/commands/archive'
require 'autoparts/commands/start'
require 'autoparts/commands/stop'
require 'autoparts/commands/restart'
require 'autoparts/commands/status'
require 'autoparts/commands/update'
require 'autoparts/commands/upload'

module Autoparts
end
